<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Vehicule extends \App\Entity\Vehicule implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'label', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'marque_id', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'modele_id', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'type_id', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'user_id', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'type_moteur_id', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'groupe_id', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'annee', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'kilometrage', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'immatriculation', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'images', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'date_exp_inscription', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'date_exp_licence', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'en_service', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'coursier', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'date_circulation', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'numero_chassis', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'seats', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'marque', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'modele', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'user'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'label', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'marque_id', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'modele_id', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'type_id', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'user_id', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'type_moteur_id', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'groupe_id', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'annee', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'kilometrage', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'immatriculation', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'images', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'date_exp_inscription', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'date_exp_licence', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'en_service', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'coursier', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'date_circulation', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'numero_chassis', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'seats', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'marque', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'modele', '' . "\0" . 'App\\Entity\\Vehicule' . "\0" . 'user'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Vehicule $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getMarque(): ?\App\Entity\Marque
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarque', []);

        return parent::getMarque();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarque(?\App\Entity\Marque $marque): \App\Entity\Vehicule
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarque', [$marque]);

        return parent::setMarque($marque);
    }

    /**
     * {@inheritDoc}
     */
    public function getModele(): ?\App\Entity\Modele
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModele', []);

        return parent::getModele();
    }

    /**
     * {@inheritDoc}
     */
    public function setModele(?\App\Entity\Modele $modele): \App\Entity\Vehicule
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModele', [$modele]);

        return parent::setModele($modele);
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getLabel(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLabel', []);

        return parent::getLabel();
    }

    /**
     * {@inheritDoc}
     */
    public function setLabel(?string $label): \App\Entity\Vehicule
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLabel', [$label]);

        return parent::setLabel($label);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarqueId(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarqueId', []);

        return parent::getMarqueId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarqueId(int $marque_id): \App\Entity\Vehicule
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarqueId', [$marque_id]);

        return parent::setMarqueId($marque_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getModeleId(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModeleId', []);

        return parent::getModeleId();
    }

    /**
     * {@inheritDoc}
     */
    public function setModeleId(int $modele_id): \App\Entity\Vehicule
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModeleId', [$modele_id]);

        return parent::setModeleId($modele_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeId(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeId', []);

        return parent::getTypeId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeId(int $type_id): \App\Entity\Vehicule
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeId', [$type_id]);

        return parent::setTypeId($type_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeMoteurId(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeMoteurId', []);

        return parent::getTypeMoteurId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeMoteurId(int $type_moteur_id): \App\Entity\Vehicule
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeMoteurId', [$type_moteur_id]);

        return parent::setTypeMoteurId($type_moteur_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getGroupeId(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroupeId', []);

        return parent::getGroupeId();
    }

    /**
     * {@inheritDoc}
     */
    public function setGroupeId(int $groupe_id): \App\Entity\Vehicule
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGroupeId', [$groupe_id]);

        return parent::setGroupeId($groupe_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnee(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnee', []);

        return parent::getAnnee();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnnee(int $annee): \App\Entity\Vehicule
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnnee', [$annee]);

        return parent::setAnnee($annee);
    }

    /**
     * {@inheritDoc}
     */
    public function getKilometrage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKilometrage', []);

        return parent::getKilometrage();
    }

    /**
     * {@inheritDoc}
     */
    public function setKilometrage(?string $kilometrage): \App\Entity\Vehicule
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKilometrage', [$kilometrage]);

        return parent::setKilometrage($kilometrage);
    }

    /**
     * {@inheritDoc}
     */
    public function getImmatriculation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImmatriculation', []);

        return parent::getImmatriculation();
    }

    /**
     * {@inheritDoc}
     */
    public function setImmatriculation(?string $immatriculation): \App\Entity\Vehicule
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImmatriculation', [$immatriculation]);

        return parent::setImmatriculation($immatriculation);
    }

    /**
     * {@inheritDoc}
     */
    public function getImages(): ?array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImages', []);

        return parent::getImages();
    }

    /**
     * {@inheritDoc}
     */
    public function setImages(?array $images): \App\Entity\Vehicule
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImages', [$images]);

        return parent::setImages($images);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateExpInscription(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateExpInscription', []);

        return parent::getDateExpInscription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateExpInscription(?\DateTimeInterface $date_exp_inscription): \App\Entity\Vehicule
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateExpInscription', [$date_exp_inscription]);

        return parent::setDateExpInscription($date_exp_inscription);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateExpLicence(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateExpLicence', []);

        return parent::getDateExpLicence();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateExpLicence(?\DateTimeInterface $date_exp_licence): \App\Entity\Vehicule
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateExpLicence', [$date_exp_licence]);

        return parent::setDateExpLicence($date_exp_licence);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnService(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnService', []);

        return parent::getEnService();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnService(?bool $en_service): \App\Entity\Vehicule
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnService', [$en_service]);

        return parent::setEnService($en_service);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoursier(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoursier', []);

        return parent::getCoursier();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoursier(?\App\Entity\User $coursier): \App\Entity\Vehicule
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoursier', [$coursier]);

        return parent::setCoursier($coursier);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCirculation(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCirculation', []);

        return parent::getDateCirculation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCirculation(?\DateTimeInterface $date_circulation): \App\Entity\Vehicule
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCirculation', [$date_circulation]);

        return parent::setDateCirculation($date_circulation);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroChassis(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroChassis', []);

        return parent::getNumeroChassis();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroChassis(?string $numero_chassis): \App\Entity\Vehicule
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroChassis', [$numero_chassis]);

        return parent::setNumeroChassis($numero_chassis);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeats(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeats', []);

        return parent::getSeats();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeats(int $seats): \App\Entity\Vehicule
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeats', [$seats]);

        return parent::setSeats($seats);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(?\App\Entity\User $user): \App\Entity\Vehicule
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
