<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Navette extends \App\Entity\Navette implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'user_id', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'vehicule_id', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'trajet_id', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'societe_id', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'tarif', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'date_navette', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'start_at', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'end_at', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'direction', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'zone', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'heure_navette', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'comment', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'duree', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'distance', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'duree_up', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'distance_up', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'pickupLatitude', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'pickupLongitude', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'dropoffLatitude', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'dropoffLongitude', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'pickupLocation', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'dropoffLocation', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'nom_trajet', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'vehicule', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'trajet', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'societe', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'entries'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'user_id', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'vehicule_id', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'trajet_id', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'societe_id', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'tarif', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'date_navette', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'start_at', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'end_at', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'direction', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'zone', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'heure_navette', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'comment', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'duree', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'distance', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'duree_up', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'distance_up', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'pickupLatitude', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'pickupLongitude', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'dropoffLatitude', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'dropoffLongitude', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'pickupLocation', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'dropoffLocation', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'nom_trajet', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'vehicule', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'trajet', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'societe', '' . "\0" . 'App\\Entity\\Navette' . "\0" . 'entries'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Navette $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTarif(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTarif', []);

        return parent::getTarif();
    }

    /**
     * {@inheritDoc}
     */
    public function setTarif(string $tarif): \App\Entity\Navette
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTarif', [$tarif]);

        return parent::setTarif($tarif);
    }

    /**
     * {@inheritDoc}
     */
    public function getDirection(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDirection', []);

        return parent::getDirection();
    }

    /**
     * {@inheritDoc}
     */
    public function setDirection(string $direction): \App\Entity\Navette
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDirection', [$direction]);

        return parent::setDirection($direction);
    }

    /**
     * {@inheritDoc}
     */
    public function getZone(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZone', []);

        return parent::getZone();
    }

    /**
     * {@inheritDoc}
     */
    public function setZone(string $zone): \App\Entity\Navette
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZone', [$zone]);

        return parent::setZone($zone);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeureNavette(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeureNavette', []);

        return parent::getHeureNavette();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeureNavette(int $heure_navette): \App\Entity\Navette
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeureNavette', [$heure_navette]);

        return parent::setHeureNavette($heure_navette);
    }

    /**
     * {@inheritDoc}
     */
    public function getComment(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComment', []);

        return parent::getComment();
    }

    /**
     * {@inheritDoc}
     */
    public function setComment(?string $comment): \App\Entity\Navette
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComment', [$comment]);

        return parent::setComment($comment);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(?string $status): \App\Entity\Navette
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(?\App\Entity\User $user): \App\Entity\Navette
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getVehicule(): ?\App\Entity\Vehicule
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVehicule', []);

        return parent::getVehicule();
    }

    /**
     * {@inheritDoc}
     */
    public function setVehicule(?\App\Entity\Vehicule $vehicule): \App\Entity\Navette
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVehicule', [$vehicule]);

        return parent::setVehicule($vehicule);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomTrajet(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomTrajet', []);

        return parent::getNomTrajet();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomTrajet(string $nom_trajet): \App\Entity\Navette
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomTrajet', [$nom_trajet]);

        return parent::setNomTrajet($nom_trajet);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrajet(): ?\App\Entity\Trajet
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrajet', []);

        return parent::getTrajet();
    }

    /**
     * {@inheritDoc}
     */
    public function setTrajet(?\App\Entity\Trajet $trajet): \App\Entity\Navette
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrajet', [$trajet]);

        return parent::setTrajet($trajet);
    }

    /**
     * {@inheritDoc}
     */
    public function getSociete(): ?\App\Entity\Societe
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSociete', []);

        return parent::getSociete();
    }

    /**
     * {@inheritDoc}
     */
    public function setSociete(?\App\Entity\Societe $societe): \App\Entity\Navette
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSociete', [$societe]);

        return parent::setSociete($societe);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntries(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntries', []);

        return parent::getEntries();
    }

    /**
     * {@inheritDoc}
     */
    public function addEntry(\App\Entity\ReservationEntries $entry): \App\Entity\Navette
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEntry', [$entry]);

        return parent::addEntry($entry);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateNavette(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateNavette', []);

        return parent::getDateNavette();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateNavette(\DateTimeInterface $date_navette): \App\Entity\Navette
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateNavette', [$date_navette]);

        return parent::setDateNavette($date_navette);
    }

    /**
     * {@inheritDoc}
     */
    public function getStartAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartAt', []);

        return parent::getStartAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartAt(\DateTimeInterface $start_at): \App\Entity\Navette
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartAt', [$start_at]);

        return parent::setStartAt($start_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndAt', []);

        return parent::getEndAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndtAt(\DateTimeInterface $end_at): \App\Entity\Navette
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndtAt', [$end_at]);

        return parent::setEndtAt($end_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getDuree(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDuree', []);

        return parent::getDuree();
    }

    /**
     * {@inheritDoc}
     */
    public function setDuree(?string $duree): \App\Entity\Navette
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDuree', [$duree]);

        return parent::setDuree($duree);
    }

    /**
     * {@inheritDoc}
     */
    public function getDistance(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDistance', []);

        return parent::getDistance();
    }

    /**
     * {@inheritDoc}
     */
    public function setDistance(?float $distance): \App\Entity\Navette
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDistance', [$distance]);

        return parent::setDistance($distance);
    }

    /**
     * {@inheritDoc}
     */
    public function getDureeUp(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDureeUp', []);

        return parent::getDureeUp();
    }

    /**
     * {@inheritDoc}
     */
    public function setDureeUp(?string $duree_up): \App\Entity\Navette
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDureeUp', [$duree_up]);

        return parent::setDureeUp($duree_up);
    }

    /**
     * {@inheritDoc}
     */
    public function getDistanceUp(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDistanceUp', []);

        return parent::getDistanceUp();
    }

    /**
     * {@inheritDoc}
     */
    public function setDistanceUp(?float $distance_up): \App\Entity\Navette
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDistanceUp', [$distance_up]);

        return parent::setDistanceUp($distance_up);
    }

    /**
     * {@inheritDoc}
     */
    public function getPickupLatitude(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPickupLatitude', []);

        return parent::getPickupLatitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setPickupLatitude(?float $pickupLatitude): \App\Entity\Navette
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPickupLatitude', [$pickupLatitude]);

        return parent::setPickupLatitude($pickupLatitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getPickupLongitude(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPickupLongitude', []);

        return parent::getPickupLongitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setPickupLongitude(?float $pickupLongitude): \App\Entity\Navette
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPickupLongitude', [$pickupLongitude]);

        return parent::setPickupLongitude($pickupLongitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getDropoffLatitude(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDropoffLatitude', []);

        return parent::getDropoffLatitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setDropoffLatitude(?float $dropoffLatitude): \App\Entity\Navette
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDropoffLatitude', [$dropoffLatitude]);

        return parent::setDropoffLatitude($dropoffLatitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getDropoffLongitude(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDropoffLongitude', []);

        return parent::getDropoffLongitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setDropoffLongitude(?float $dropoffLongitude): \App\Entity\Navette
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDropoffLongitude', [$dropoffLongitude]);

        return parent::setDropoffLongitude($dropoffLongitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getPickupLocation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPickupLocation', []);

        return parent::getPickupLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setPickupLocation(?string $pickupLocation): \App\Entity\Navette
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPickupLocation', [$pickupLocation]);

        return parent::setPickupLocation($pickupLocation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDropoffLocation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDropoffLocation', []);

        return parent::getDropoffLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDropoffLocation(?string $dropoffLocation): \App\Entity\Navette
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDropoffLocation', [$dropoffLocation]);

        return parent::setDropoffLocation($dropoffLocation);
    }

    /**
     * {@inheritDoc}
     */
    public function getCap()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCap', []);

        return parent::getCap();
    }

    /**
     * {@inheritDoc}
     */
    public function getTaux()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaux', []);

        return parent::getTaux();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderedSeats()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderedSeats', []);

        return parent::getOrderedSeats();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
