<?php

namespace ContainerZoYn2di;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PeIkZgOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PeIkZgO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PeIkZgO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'csrfTokenManager' => ['services', '.container.private.security.csrf.token_manager', 'get_Container_Private_Security_Csrf_TokenManagerService', true],
            'encoder' => ['services', '.container.private.security.password_encoder', 'get_Container_Private_Security_PasswordEncoderService', true],
            'translator' => ['services', 'translator', 'getTranslatorService', false],
        ], [
            'csrfTokenManager' => '?',
            'encoder' => '?',
            'translator' => '?',
        ]);
    }
}
