<?php

namespace ContainerZoYn2di;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I1P5WdLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.i1P5WdL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.i1P5WdL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'navette' => ['privates', '.errored..service_locator.i1P5WdL.App\\Entity\\Navette', NULL, 'Cannot autowire service ".service_locator.i1P5WdL": it references class "App\\Entity\\Navette" but no such service exists.'],
            'translator' => ['services', 'translator', 'getTranslatorService', false],
        ], [
            'em' => '?',
            'navette' => 'App\\Entity\\Navette',
            'translator' => '?',
        ]);
    }
}
