<?php

namespace ContainerZoYn2di;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YDeArgdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yDeArgd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yDeArgd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mapQuestService' => ['privates', 'App\\Service\\MapQuestService', 'getMapQuestServiceService', true],
        ], [
            'mapQuestService' => 'App\\Service\\MapQuestService',
        ]);
    }
}
