<?php

namespace ContainerZoYn2di;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnnonceRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\AnnonceRepository' shared autowired service.
     *
     * @return \App\Repository\AnnonceRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'AnnonceRepository.php';

        return $container->privates['App\\Repository\\AnnonceRepository'] = new \App\Repository\AnnonceRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
