<?php

namespace ContainerZoYn2di;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNavetteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.B2BTaq9.App\Entity\Navette' shared service.
     *
     * @return \App\Entity\Navette
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.B2BTaq9": it references class "App\\Entity\\Navette" but no such service exists.');
    }
}
