<?php

namespace ContainerZoYn2di;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPickupRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\PickupRepository' shared autowired service.
     *
     * @return \App\Repository\PickupRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'PickupRepository.php';

        return $container->privates['App\\Repository\\PickupRepository'] = new \App\Repository\PickupRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
