<?php

namespace ContainerZoYn2di;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSocieteRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\SocieteRepository' shared autowired service.
     *
     * @return \App\Repository\SocieteRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'SocieteRepository.php';

        return $container->privates['App\\Repository\\SocieteRepository'] = new \App\Repository\SocieteRepository(($container->services['doctrine'] ?? $container->getDoctrineService()), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
