<?php

namespace ContainerZoYn2di;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserSubscriptionManagerRegistryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'BenTools\WebPushBundle\Model\Subscription\UserSubscriptionManagerRegistry' shared service.
     *
     * @return \BenTools\WebPushBundle\Model\Subscription\UserSubscriptionManagerRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'bentools'.\DIRECTORY_SEPARATOR.'webpush-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Model'.\DIRECTORY_SEPARATOR.'Subscription'.\DIRECTORY_SEPARATOR.'UserSubscriptionManagerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'bentools'.\DIRECTORY_SEPARATOR.'webpush-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Model'.\DIRECTORY_SEPARATOR.'Subscription'.\DIRECTORY_SEPARATOR.'UserSubscriptionManagerRegistry.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'UserSubscriptionManager.php';

        $container->privates['BenTools\\WebPushBundle\\Model\\Subscription\\UserSubscriptionManagerRegistry'] = $instance = new \BenTools\WebPushBundle\Model\Subscription\UserSubscriptionManagerRegistry();

        $instance->register('App\\Entity\\User', new \App\Service\UserSubscriptionManager(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService())));

        return $instance;
    }
}
