#index:
#    path: /
#    controller: App\Controller\DefaultController::index

bentools_webpush:
  resource: '@WebPushBundle/Resources/config/routing.xml'
  prefix: /webpush


# config/routes.yaml
preview_report:
    path: /generate-report/{reportType}/preview
    controller: App\Controller\Admin\ReportController::previewReport
    methods: GET



