# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    mail.sender: contact@stjg.ma
    mail.replyTo: noreply@stjg.ma
    env(COOKIE_LIFETIME): 300

services:



    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
    
    BOMO\IcalBundle\Provider\IcsProvider:
        autowire: true

    my.oauth_aware.user_provider.service:
        class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider

    App\Service\UserSubscriptionManager:
        class: App\Service\UserSubscriptionManager
        tags:
            - { name: bentools_webpush.subscription_manager, user_class: 'App\Entity\User' }

    #App\Service\GeocodingService:
        #arguments:
            #$apiKey: '%env(GOOGLE_MAPS_API_KEY)%'

    App\Service\MapQuestService:
        arguments:
            $apiKey: '%env(MAPQUEST_API_KEY)%'

