<?php

namespace ContainerBdj3RN6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SmuGVUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.smuG_VU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.smuG_VU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'navette' => ['privates', '.errored..service_locator.smuG_VU.App\\Entity\\Navette', NULL, 'Cannot autowire service ".service_locator.smuG_VU": it references class "App\\Entity\\Navette" but no such service exists.'],
        ], [
            'navette' => 'App\\Entity\\Navette',
        ]);
    }
}
