<?php

namespace ContainerBdj3RN6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCron_ExecutorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'cron.executor' shared service.
     *
     * @return \Cron\Executor\Executor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'cron'.\DIRECTORY_SEPARATOR.'cron'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Executor'.\DIRECTORY_SEPARATOR.'ExecutorInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'cron'.\DIRECTORY_SEPARATOR.'cron'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Executor'.\DIRECTORY_SEPARATOR.'Executor.php';

        return $container->services['cron.executor'] = new \Cron\Executor\Executor();
    }
}
