<?php

namespace ContainerBdj3RN6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHwiOauth_ResourceOwner_AzureService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'hwi_oauth.resource_owner.azure' shared service.
     *
     * @return \HWI\Bundle\OAuthBundle\OAuth\ResourceOwner\AzureResourceOwner
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'hwi'.\DIRECTORY_SEPARATOR.'oauth-bundle'.\DIRECTORY_SEPARATOR.'OAuth'.\DIRECTORY_SEPARATOR.'ResourceOwnerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'hwi'.\DIRECTORY_SEPARATOR.'oauth-bundle'.\DIRECTORY_SEPARATOR.'OAuth'.\DIRECTORY_SEPARATOR.'ResourceOwner'.\DIRECTORY_SEPARATOR.'AbstractResourceOwner.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'hwi'.\DIRECTORY_SEPARATOR.'oauth-bundle'.\DIRECTORY_SEPARATOR.'OAuth'.\DIRECTORY_SEPARATOR.'ResourceOwner'.\DIRECTORY_SEPARATOR.'GenericOAuth2ResourceOwner.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'hwi'.\DIRECTORY_SEPARATOR.'oauth-bundle'.\DIRECTORY_SEPARATOR.'OAuth'.\DIRECTORY_SEPARATOR.'ResourceOwner'.\DIRECTORY_SEPARATOR.'AzureResourceOwner.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'psr'.\DIRECTORY_SEPARATOR.'http-client'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'ClientInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'php-http'.\DIRECTORY_SEPARATOR.'httplug'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'HttpClient.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'php-http'.\DIRECTORY_SEPARATOR.'client-common'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'HttpMethodsClientInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'php-http'.\DIRECTORY_SEPARATOR.'client-common'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'HttpMethodsClient.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'hwi'.\DIRECTORY_SEPARATOR.'oauth-bundle'.\DIRECTORY_SEPARATOR.'OAuth'.\DIRECTORY_SEPARATOR.'RequestDataStorageInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'hwi'.\DIRECTORY_SEPARATOR.'oauth-bundle'.\DIRECTORY_SEPARATOR.'OAuth'.\DIRECTORY_SEPARATOR.'RequestDataStorage'.\DIRECTORY_SEPARATOR.'SessionStorage.php';

        return $container->services['hwi_oauth.resource_owner.azure'] = new \HWI\Bundle\OAuthBundle\OAuth\ResourceOwner\AzureResourceOwner(new \Http\Client\Common\HttpMethodsClient(($container->services['hwi_oauth.http.client'] ?? $container->load('getHwiOauth_Http_ClientService')), ($container->services['hwi_oauth.http.message_factory'] ?? $container->load('getHwiOauth_Http_MessageFactoryService'))), ($container->privates['security.http_utils'] ?? $container->getSecurity_HttpUtilsService()), ['client_id' => $container->getEnv('AZURE_CLIENT_ID'), 'client_secret' => $container->getEnv('AZURE_CLIENT_SECRET'), 'scope' => 'User.Read offline_access', 'options' => ['infos_url' => 'https://graph.microsoft.com/v1.0/me', 'application' => 'common', 'csrf' => true], 'paths' => []], 'azure', new \HWI\Bundle\OAuthBundle\OAuth\RequestDataStorage\SessionStorage(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()))));
    }
}
