<?php

namespace ContainerBdj3RN6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMapQuestServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\MapQuestService' shared autowired service.
     *
     * @return \App\Service\MapQuestService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'MapQuestService.php';

        return $container->privates['App\\Service\\MapQuestService'] = new \App\Service\MapQuestService(($container->privates['.debug.http_client'] ?? $container->get_Debug_HttpClientService()), $container->getEnv('MAPQUEST_API_KEY'));
    }
}
