<?php

namespace Container0oIkxma;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B2BTaq9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.B2BTaq9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.B2BTaq9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'navette' => ['privates', '.errored..service_locator.B2BTaq9.App\\Entity\\Navette', NULL, 'Cannot autowire service ".service_locator.B2BTaq9": it references class "App\\Entity\\Navette" but no such service exists.'],
        ], [
            'em' => '?',
            'navette' => 'App\\Entity\\Navette',
        ]);
    }
}
