<?php

namespace Container0oIkxma;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BrKFY7qService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.brKFY7q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.brKFY7q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'table' => ['privates', 'App\\Service\\Table', 'getTableService', true],
            'translator' => ['services', 'translator', 'getTranslatorService', false],
        ], [
            'table' => 'App\\Service\\Table',
            'translator' => '?',
        ]);
    }
}
