<?php

namespace Container0oIkxma;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_RegistryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'form.registry' shared service.
     *
     * @return \Symfony\Component\Form\FormRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormRegistryInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormRegistry.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormExtensionInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'Extension'.\DIRECTORY_SEPARATOR.'DependencyInjection'.\DIRECTORY_SEPARATOR.'DependencyInjectionExtension.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'ResolvedFormTypeFactoryInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'Extension'.\DIRECTORY_SEPARATOR.'DataCollector'.\DIRECTORY_SEPARATOR.'Proxy'.\DIRECTORY_SEPARATOR.'ResolvedTypeFactoryDataCollectorProxy.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'ResolvedFormTypeFactory.php';

        return $container->privates['form.registry'] = new \Symfony\Component\Form\FormRegistry([0 => new \Symfony\Component\Form\Extension\DependencyInjection\DependencyInjectionExtension(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Form\\AnnonceType' => ['privates', 'App\\Form\\AnnonceType', 'getAnnonceTypeService', true],
            'App\\Form\\CategoryType' => ['privates', 'App\\Form\\CategoryType', 'getCategoryTypeService', true],
            'App\\Form\\ExcelUploadType' => ['privates', 'App\\Form\\ExcelUploadType', 'getExcelUploadTypeService', true],
            'App\\Form\\MarqueType' => ['privates', 'App\\Form\\MarqueType', 'getMarqueTypeService', true],
            'App\\Form\\ModeleType' => ['privates', 'App\\Form\\ModeleType', 'getModeleTypeService', true],
            'App\\Form\\NavetteType' => ['privates', 'App\\Form\\NavetteType', 'getNavetteTypeService', true],
            'App\\Form\\PickupType' => ['privates', 'App\\Form\\PickupType', 'getPickupTypeService', true],
            'App\\Form\\ReclamationType' => ['privates', 'App\\Form\\ReclamationType', 'getReclamationTypeService', true],
            'App\\Form\\ReservationEntriesType' => ['privates', 'App\\Form\\ReservationEntriesType', 'getReservationEntriesTypeService', true],
            'App\\Form\\ReservationType' => ['privates', 'App\\Form\\ReservationType', 'getReservationTypeService', true],
            'App\\Form\\Search\\AnnonceSearchType' => ['privates', 'App\\Form\\Search\\AnnonceSearchType', 'getAnnonceSearchTypeService', true],
            'App\\Form\\Search\\CategorySearchType' => ['privates', 'App\\Form\\Search\\CategorySearchType', 'getCategorySearchTypeService', true],
            'App\\Form\\Search\\MarqueSearchType' => ['privates', 'App\\Form\\Search\\MarqueSearchType', 'getMarqueSearchTypeService', true],
            'App\\Form\\Search\\ModeleSearchType' => ['privates', 'App\\Form\\Search\\ModeleSearchType', 'getModeleSearchTypeService', true],
            'App\\Form\\Search\\NavetteSearchType' => ['privates', 'App\\Form\\Search\\NavetteSearchType', 'getNavetteSearchTypeService', true],
            'App\\Form\\Search\\PickupSearchType' => ['privates', 'App\\Form\\Search\\PickupSearchType', 'getPickupSearchTypeService', true],
            'App\\Form\\Search\\ReclamationSearchType' => ['privates', 'App\\Form\\Search\\ReclamationSearchType', 'getReclamationSearchTypeService', true],
            'App\\Form\\Search\\ReservationEntriesSearchType' => ['privates', 'App\\Form\\Search\\ReservationEntriesSearchType', 'getReservationEntriesSearchTypeService', true],
            'App\\Form\\Search\\ReservationSearchType' => ['privates', 'App\\Form\\Search\\ReservationSearchType', 'getReservationSearchTypeService', true],
            'App\\Form\\Search\\ShiftSearchType' => ['privates', 'App\\Form\\Search\\ShiftSearchType', 'getShiftSearchTypeService', true],
            'App\\Form\\Search\\SiteSearchType' => ['privates', 'App\\Form\\Search\\SiteSearchType', 'getSiteSearchTypeService', true],
            'App\\Form\\Search\\TarifSearchType' => ['privates', 'App\\Form\\Search\\TarifSearchType', 'getTarifSearchTypeService', true],
            'App\\Form\\Search\\TrajetSearchType' => ['privates', 'App\\Form\\Search\\TrajetSearchType', 'getTrajetSearchTypeService', true],
            'App\\Form\\Search\\UserSearchType' => ['privates', 'App\\Form\\Search\\UserSearchType', 'getUserSearchTypeService', true],
            'App\\Form\\Search\\VehiculeSearchType' => ['privates', 'App\\Form\\Search\\VehiculeSearchType', 'getVehiculeSearchTypeService', true],
            'App\\Form\\SettingType' => ['privates', 'App\\Form\\SettingType', 'getSettingTypeService', true],
            'App\\Form\\ShiftType' => ['privates', 'App\\Form\\ShiftType', 'getShiftTypeService', true],
            'App\\Form\\SiteType' => ['privates', 'App\\Form\\SiteType', 'getSiteTypeService', true],
            'App\\Form\\SocieteType' => ['privates', 'App\\Form\\SocieteType', 'getSocieteTypeService', true],
            'App\\Form\\TarifType' => ['privates', 'App\\Form\\TarifType', 'getTarifTypeService', true],
            'App\\Form\\TrajetType' => ['privates', 'App\\Form\\TrajetType', 'getTrajetTypeService', true],
            'App\\Form\\Type\\AjaxUploadType' => ['privates', 'App\\Form\\Type\\AjaxUploadType', 'getAjaxUploadTypeService', true],
            'App\\Form\\Type\\FieldsetType' => ['privates', 'App\\Form\\Type\\FieldsetType', 'getFieldsetTypeService', true],
            'App\\Form\\UserType' => ['privates', 'App\\Form\\UserType', 'getUserTypeService', true],
            'App\\Form\\VehiculeType' => ['privates', 'App\\Form\\VehiculeType', 'getVehiculeTypeService', true],
            'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => ['privates', 'form.type.entity', 'getForm_Type_EntityService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => ['privates', 'form.type.choice', 'getForm_Type_ChoiceService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ColorType' => ['privates', 'form.type.color', 'getForm_Type_ColorService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FileType' => ['services', '.container.private.form.type.file', 'get_Container_Private_Form_Type_FileService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => ['privates', 'form.type.form', 'getForm_Type_FormService', true],
        ], [
            'App\\Form\\AnnonceType' => '?',
            'App\\Form\\CategoryType' => '?',
            'App\\Form\\ExcelUploadType' => '?',
            'App\\Form\\MarqueType' => '?',
            'App\\Form\\ModeleType' => '?',
            'App\\Form\\NavetteType' => '?',
            'App\\Form\\PickupType' => '?',
            'App\\Form\\ReclamationType' => '?',
            'App\\Form\\ReservationEntriesType' => '?',
            'App\\Form\\ReservationType' => '?',
            'App\\Form\\Search\\AnnonceSearchType' => '?',
            'App\\Form\\Search\\CategorySearchType' => '?',
            'App\\Form\\Search\\MarqueSearchType' => '?',
            'App\\Form\\Search\\ModeleSearchType' => '?',
            'App\\Form\\Search\\NavetteSearchType' => '?',
            'App\\Form\\Search\\PickupSearchType' => '?',
            'App\\Form\\Search\\ReclamationSearchType' => '?',
            'App\\Form\\Search\\ReservationEntriesSearchType' => '?',
            'App\\Form\\Search\\ReservationSearchType' => '?',
            'App\\Form\\Search\\ShiftSearchType' => '?',
            'App\\Form\\Search\\SiteSearchType' => '?',
            'App\\Form\\Search\\TarifSearchType' => '?',
            'App\\Form\\Search\\TrajetSearchType' => '?',
            'App\\Form\\Search\\UserSearchType' => '?',
            'App\\Form\\Search\\VehiculeSearchType' => '?',
            'App\\Form\\SettingType' => '?',
            'App\\Form\\ShiftType' => '?',
            'App\\Form\\SiteType' => '?',
            'App\\Form\\SocieteType' => '?',
            'App\\Form\\TarifType' => '?',
            'App\\Form\\TrajetType' => '?',
            'App\\Form\\Type\\AjaxUploadType' => '?',
            'App\\Form\\Type\\FieldsetType' => '?',
            'App\\Form\\UserType' => '?',
            'App\\Form\\VehiculeType' => '?',
            'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ColorType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FileType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => '?',
        ]), ['Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.form.transformation_failure_handling'] ?? $container->load('getForm_TypeExtension_Form_TransformationFailureHandlingService'));
            yield 1 => ($container->privates['form.type_extension.form.http_foundation'] ?? $container->load('getForm_TypeExtension_Form_HttpFoundationService'));
            yield 2 => ($container->privates['form.type_extension.form.validator'] ?? $container->load('getForm_TypeExtension_Form_ValidatorService'));
            yield 3 => ($container->privates['form.type_extension.upload.validator'] ?? $container->load('getForm_TypeExtension_Upload_ValidatorService'));
            yield 4 => ($container->privates['form.type_extension.csrf'] ?? $container->load('getForm_TypeExtension_CsrfService'));
            yield 5 => ($container->privates['form.type_extension.form.data_collector'] ?? $container->load('getForm_TypeExtension_Form_DataCollectorService'));
        }, 6), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\RepeatedType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.repeated.validator'] ?? ($container->privates['form.type_extension.repeated.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\RepeatedTypeValidatorExtension()));
        }, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\SubmitType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.submit.validator'] ?? ($container->privates['form.type_extension.submit.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\SubmitTypeValidatorExtension()));
        }, 1)], new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_guesser.validator'] ?? $container->load('getForm_TypeGuesser_ValidatorService'));
            yield 1 => ($container->privates['form.type_guesser.doctrine'] ?? $container->load('getForm_TypeGuesser_DoctrineService'));
        }, 2))], new \Symfony\Component\Form\Extension\DataCollector\Proxy\ResolvedTypeFactoryDataCollectorProxy(new \Symfony\Component\Form\ResolvedFormTypeFactory(), ($container->privates['data_collector.form'] ?? $container->getDataCollector_FormService())));
    }
}
