<?php

namespace Container0oIkxma;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLinkCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\LinkCommand' shared autowired service.
     *
     * @return \App\Command\LinkCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'LinkCommand.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'bentools'.\DIRECTORY_SEPARATOR.'webpush-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Sender'.\DIRECTORY_SEPARATOR.'PushMessagerSenderInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'bentools'.\DIRECTORY_SEPARATOR.'webpush-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Sender'.\DIRECTORY_SEPARATOR.'PushMessageSender.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'UserSubscriptionNotification.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());
        $b = new \BenTools\WebPushBundle\Sender\PushMessageSender(['VAPID' => ['subject' => 'localhost', 'publicKey' => 'BDMoknezav3-yWOZ4d60vl1rcTCnKwhzVHs0CctZZ4a2IVXehyClDKzHRAzuAYzNBmi3wZMSXctcI8mpIadUk1E', 'privateKey' => 'XSxTnOveiVOdvhzZ3knQqwmJLQuQiPqvEIqUyVOvnQY']]);

        $container->privates['App\\Command\\LinkCommand'] = $instance = new \App\Command\LinkCommand($a, ($container->privates['BenTools\\WebPushBundle\\Model\\Subscription\\UserSubscriptionManagerRegistry'] ?? $container->load('getUserSubscriptionManagerRegistryService')), $b, new \App\Service\UserSubscriptionNotification($b, $a));

        $instance->setName('link:check');

        return $instance;
    }
}
