<?php

namespace Container0oIkxma;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMarqueRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\MarqueRepository' shared autowired service.
     *
     * @return \App\Repository\MarqueRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'MarqueRepository.php';

        return $container->privates['App\\Repository\\MarqueRepository'] = new \App\Repository\MarqueRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
