<?php

namespace Container0oIkxma;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTableService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Table' shared autowired service.
     *
     * @return \App\Service\Table
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Table.php';

        $a = ($container->services['.container.private.twig'] ?? $container->get_Container_Private_TwigService());

        if (isset($container->privates['App\\Service\\Table'])) {
            return $container->privates['App\\Service\\Table'];
        }

        return $container->privates['App\\Service\\Table'] = new \App\Service\Table($a, ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
