<?php

namespace Container0oIkxma;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTarifRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\TarifRepository' shared autowired service.
     *
     * @return \App\Repository\TarifRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'TarifRepository.php';

        return $container->privates['App\\Repository\\TarifRepository'] = new \App\Repository\TarifRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
