<?php

namespace Container0oIkxma;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWebPushGenerateKeysCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'BenTools\WebPushBundle\Command\WebPushGenerateKeysCommand' shared service.
     *
     * @return \BenTools\WebPushBundle\Command\WebPushGenerateKeysCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'bentools'.\DIRECTORY_SEPARATOR.'webpush-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'WebPushGenerateKeysCommand.php';

        $container->privates['BenTools\\WebPushBundle\\Command\\WebPushGenerateKeysCommand'] = $instance = new \BenTools\WebPushBundle\Command\WebPushGenerateKeysCommand();

        $instance->setName('webpush:generate:keys');

        return $instance;
    }
}
