<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0oIkxma\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0oIkxma/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0oIkxma.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0oIkxma\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0oIkxma\App_KernelDevDebugContainer([
    'container.build_hash' => '0oIkxma',
    'container.build_id' => 'b9a29957',
    'container.build_time' => 1740951414,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0oIkxma');
