<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTRpcNve\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTRpcNve/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTRpcNve.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTRpcNve\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTRpcNve\App_KernelDevDebugContainer([
    'container.build_hash' => 'TRpcNve',
    'container.build_id' => 'eb597954',
    'container.build_time' => 1741316410,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTRpcNve');
