<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZoYn2di\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZoYn2di/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZoYn2di.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZoYn2di\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZoYn2di\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZoYn2di',
    'container.build_id' => '2726d71a',
    'container.build_time' => 1738884748,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZoYn2di');
